steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/php-base:$TAG_NAME'
  - '.'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
images:
- 'gcr.io/$PROJECT_ID/php-base:$TAG_NAME'
options:
  logging: CLOUD_LOGGING_ONLY # Or NONE for no logging
